# Generated by Django 3.2.16 on 2023-08-30 23:53

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_follow_no_self_following'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='no_self_following',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(('user', django.db.models.expressions.F('following')), _negated=True), name='no_self_following'),
        ),
    ]
